import { Header } from "@/components/header";
import "@/styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`grid min-h-screen grid-rows-[5vh_1fr] font-sans ${inter.variable}`}
        style={{ minHeight: "100dvh" }}
      >
        <Header />
        <main className="flex flex-col items-center justify-start bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </main>
      </body>
    </html>
  );
}
