import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "@/styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`grid min-h-screen grid-rows-[minmax(5vh,auto)_1fr] font-sans ${inter.variable}`}
        style={{ minHeight: "100dvh" }}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="flex flex-col items-center justify-start">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
